### ISSUE TITLE
Why was "cdoc" added to TARGET_DOMAIN in cf-companion?

### ISSUE THREAD

**Issue by Keagel** [htpcBeginner/docker-traefik#244]
I've had to remove it in order to get everything to work for me. Is there a reason you added it?

**Comment by uasdj25** [comment]
The reason would be because that's the DNS entry that he wants to point to.  You can point cf-companion to point to a subdomain DNS record rather than your A record (best practice regarding DNS creation).  All you need to do is to manually enter a CNAME DNS record in Cloudflare for cdoc (or whatever you want to name it) that refers back to your root domain.  It should work after that.

**Comment by Keagel** [comment]
Why is it best practice for DNS creation? What does "cdoc" stand for? Just wondering what the reasoning behind those choices is.

**Comment by uasdj25** [comment]
It's just a means to have another record (CNAME) pointing to the root domain instead of pointing at the root domain directly.  If your cdoc subdomain record has an issue due to calls from cf-companion for some strange reason, then no big deal because it only affects the CNAME record instead of the DNS record pointing to your entire domain.

Honestly, you don't have to do that step.  You can leave it pointed to your root domain if you like.  I'm just extra careful when it comes to the creation of records, in case something goes awry.

As for the acronym, I honestly don't know.  I would guess it has to do with either cloudflare or the creation of dns records.  I'm unfamiliar with that acronym.

**Comment by htpcBeginner** [comment]
Sorry for this confusion. @uasdj25 has mostly answered everything.

cdoc is the hostname of my server. So I have a A record cdoc.example.com pointing to my IP. So with cf-companion target domain set to cdoc, all the services will point to the same IP as the cdoc.example.com. 

I do this because, I have multiple servers, each with their own subdomain and A record. I frequently flip DNS to different servers while testing. 

If you do not plan on switching or doing similar things as i do, then you can set the target to example.com (root domain) as @uasdj25 explains.
