### ISSUE TITLE
How to configure Sonarr/Radarr to use Jackett with OAUTH

### ISSUE THREAD

**Issue by Nighteyez07** [htpcBeginner/docker-traefik#3]
How would one go about configuration Sonarr/Radarr to use Jackett when using the OAUTH configuration? The indexer in Jackett comes back successful, but when using the TORZNAB link with API from Jackett in Sonarr or Radarr and it fails to authenticate 
 with the message "Unable to connect to indexer".

**Comment by garikaib** [comment]
You are doing it wrong you should use the traefik_proxy network i.e the internal network. The jackett host should be typed as jackett and the actual port used by Jackett i.e 9117. Whenever a hostname is asked for use the container name jn the host field.

**Comment by jonathanklingberg** [comment]
I got the same question.
I want to make sure both Jackett and sabnzbd uses the VPN provided by transmission, i.e:
network_mode: container:transmission-vpn
But then using the container name (jackett) isn't resolved to an ip.
Right now I'm using hard-coded IP's for the services but these change on server reboot which is annoying.
Would it be possible to use both the traefik_proxy network and the transmission-vpn networks in parallel or what would be the solution?

**Comment by garikaib** [comment]
You can create your own network and assign static IP addresses to services that u can use internally for inter-app communication.

**Comment by htpcBeginner** [comment]
What @garikaib said. Create your own network and assign static IPs. This is what I do with Traefik 2.

**Comment by jonathanklingberg** [comment]
Sorry but I'm a bit novice.
Here's my change:
```
     network_mode: container:transmission-vpn
-    # networks:
-    #   - traefik_proxy
+    networks:
+      traefik_proxy:
+        ipv4_address: 172.19.0.20
```
(Similar to your static IP assignment found here: https://github.com/htpcBeginner/docker-traefik/blob/master/docker-compose-t2.yml#L56-L58)
But then I get the following error:
`ERROR: 'network_mode' and 'networks' cannot be combined`
If I remove the network_mode property then I get stativ IP working but without vpn...
Are you suggesting that I should create a new network with a separate VPN configuration to replace the network_mode:container:transmission-vpn property?

**Comment by htpcBeginner** [comment]
I see your point. I am reopening this issue. @garikaib can you elaborate? If I find an answer i will let you know. Due to this reason, i have disabled oauth for jackett and calling torznab feed using https://jackett.example.com.

**Comment by Artiume** [comment]
Try using the backend label/dns name i.e. http://jackett:9117

**Comment by garikaib** [comment]
@htpcBeginner and @jonathanklingberg That's an interesting problem. Unfortunately, I don't use that setup and don't have time do look deeply into the problem. However, this should be solved by setting up seperate VPN for each container you want to forward traffic via VPN or at a VPN at host level which acts as a gateway to VPN.

**Comment by Artiume** [comment]
With docker, you can do it at the container level. My solution works, just waiting for them to try it lol.

**Comment by sseifert** [comment]
What @jonathanklingberg is referring to is to use a vpn container for another container's networking, which is different than this issue of connecting behind oauth. By using
```
network_mode: container:transmission-vpn
```
you're telling Docker to use the Transmission container as the "host". With this setup, Transmission will be available on `<TRANSMISSION_HOST_IP>:<TRANSMISSION_PORT>`, and **new_container** will be available on `<TRANSMISSION_HOST_IP>:<**new_container_PORT**>`.

You're getting an error because you can't connect the new_container to any other network - it can only use Transmission's. This means that **you can copy your traefik configuration from new_container and add it to your transmission config** in order to have traefik route correctly. Your transmission container should have the traefik config for transmission _and_ any other containers connected to it.

To get around the oauth authentication (which is provided by your Traefik service) you can use Docker networking (the container name), or a static host IP (both mentioned above), to connect to Jackett on the local network. This is the faster method anyways since it's just local traffic.

**Comment by Nighteyez07** [comment]
I should have updated my post. I was able to resolve my issue by referencing the internal ip with port for Sonarr and Radarr. 
`http://192.168.#.###:{PORT}/api/v2.0/indexers/1337x/results/torznab/`

**Comment by jonathanklingberg** [comment]
Thanks @sseifert! I managed to solve the problem by using the following jackett URL for raddarr/sonarr:
http://transmission-vpn:9117/api/v2.0/indexers/1337x/results/torznab/
@Nighteyez07, using the server ip did not work (192.168.2.29) neighter the ip for transmission-vpn container (172.18.0.2). Using the transmission-vpn container name seem to be the only way.
