### ISSUE TITLE
Have you looked at Authelia?

### ISSUE THREAD

**Issue by FAFDK** [htpcBeginner/docker-traefik#9]
Hi. Thank you for putting this work together, helping out.
I've just found "[Authelia](https://github.com/authelia/authelia)" another open-source authentication and authorization server, which works with Traefik, Nginx, etc.
Maybe it could be of some use, comes with installer scripts etc.
Have you checked it out?

**Comment by Zwordi** [comment]
Hello @FAFDK , as i’m just passing by to this repo in order to gather few tricks for my own setup i saw your post.
Yes Authelia is working with an Traefik setup, i’m using it myself with an openldap container behind to reduce the load on some service with poor authentication mechanisms integration and it’s working fine. 
In order to have it working you need to be at ease with Traefik and to follow the documentation on : 
- https://docs.authelia.com/deployment/supported-proxies/traefik2.x.html

As you open your issue on February i’m sure that you found out yourself already.

Have a nice week-end.

**Comment by FAFDK** [comment]
Thank you for your reply. I've not yet implemented Authelia or Traefik in my setup, have been waiting for Traefik v2 to become more mature. I have also moved most of my "services" out of the house. I will do some more research later on, when I get the opportunity to continue on this route.

Thank you for letting me know. Appreciate it.
